# Example annotated build data file
mod-name: ReStockPlus
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - ReStockPlus
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
    - license.txt
dependencies:  # Configure dependencies
  ModuleManager:
    location: url
    url: https://ksp.sarbian.com/jenkins/job/ModuleManager/162/artifact/ModuleManager-4.2.2.zip
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 2106  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 230112  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
